# Generated by Django 4.2.6 on 2023-10-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificate_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='token',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
