# Generated by Django 4.2.6 on 2023-10-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_alter_certificate_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='token',
        ),
    ]
